---
version: 2
jobs:
  BASE: &base # Only used to centralized some common configs
    docker:
      - image: node:latest
    working_directory: ~/cli

  installdeps:
    <<: *base
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules

  CI: &test
    <<: *base
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Build plugin
          command: npm run build
      - run:
          name: Testing
          command: npm run test
      - persist_to_workspace:
          root: ~/cli
          paths:
            - lib

  bumpprerelease:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - attach_workspace:
          at: ~/cli
      - run:
          name: Set Git Creds
          command: git config user.email "gael.motte@gmail.com" && git config user.name "Gael Motte"
      - run:
          name: Bump Preminor
          command: npm run bumpprerelease

  bumpversion:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - attach_workspace:
          at: ~/cli
      - run:
          name: Set Git Creds
          command: git config user.email "gael.motte@gmail.com" && git config user.name "Gael Motte"
      - run:
          name: Bump Minor or Patch
          command: npm run bumpversion

  publish:
    <<: *base
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  'New Code Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              ignore:
                - main
                - develop
      - CI:
          requires:
            - installdeps
  'Develop Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              only: develop
      - CI:
          requires:
            - installdeps
      - bumpprerelease:
          requires:
            - CI

  'Main Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              only: main
      - CI:
          requires:
            - installdeps
      - bumpversion:
          requires:
            - CI

  'Publish':
    jobs:
      - installdeps:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          requires:
            - installdeps
