---
version: 2
jobs:
  CI: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build plugin
          command: yarn prepack
      - run:
          name: Testing
          command: yarn test
      - persist_to_workspace:
          root: ~/cli
          paths:
            - lib
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  CD:
    <<: *test
    working_directory: ~/cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  "gmotte":
    jobs:
      - CI
      - CD:
          requires:
            - CI
          filters:
            branches:
              only: main
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
