---
version: 2
jobs:
  BASE: &base # Only used to centralized some common configs
    docker:
      - image: node:latest
    working_directory: ~/cli
  CI: &test
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build plugin
          command: npm prepack
      - run:
          name: Testing
          command: npm test
      - persist_to_workspace:
          root: ~/cli
          paths:
            - lib
            - node_modules
  cache:
    <<: *base
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
  CD:
    <<: *base
    working_directory: ~/cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  'gmotte':
    jobs:
      - CI
      - CD:
          requires:
            - CI
          filters:
            branches:
              only: main
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
